/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ChaptersFetcher;
import controller.EpubBuilder;
import controller.TTVTitlePage;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Stream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import org.apache.commons.io.FileUtils;
import userInterface.EpubMaker;
import view.component.JTextAreaOutputStream;

/**
 *
 * @author khang
 */
public class MainFrame extends javax.swing.JFrame {

	/**
	 * Creates new form MainGui2
	 */
	File templateTemp;
	public MainFrame() throws IOException {
		initComponents();
                setTitle("Tàng Thư Viện downloader");
		book = null;
		start.setEnabled(false);
		stop.setEnabled(false);
		File home = new File(System.getProperty("user.home"));
		outputFolderStr.setText(home.getAbsolutePath());
		outputFolderChooser.setSelectedFile(home);
		startDownloadMD.setEnabled(false);
		OutputStream textAreaOut = new JTextAreaOutputStream(outputTextArea);
		PrintStream textAreaStream = new PrintStream(textAreaOut);
		System.setErr(textAreaStream);
		System.setOut(textAreaStream);
		templateTemp = EpubMaker.createTempTemplateFile();
		templateFileLabel.setText(templateTemp.getAbsolutePath());
		startDownloadEpub.setEnabled(false);
		titleCheck.setSelected(true);
		coverCheck.setSelected(true);
		tableOfContent.setSelected(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNovelChooser = new view.NovelChooserDialog(this, true);
        outputFolderChooser = new javax.swing.JFileChooser();
        templateFileChooser = new javax.swing.JFileChooser();
        findNovelBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        novelURL = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        novelName = new javax.swing.JLabel();
        author = new javax.swing.JLabel();
        uploader = new javax.swing.JLabel();
        chapterNum = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        start = new javax.swing.JSpinner();
        stop = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        titleCheck = new javax.swing.JCheckBox();
        coverCheck = new javax.swing.JCheckBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        folderName = new javax.swing.JTextField();
        startDownloadMD = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        templateFileBrowserBtn = new javax.swing.JButton();
        templateFileLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        backToDefaultTemplate = new javax.swing.JButton();
        tableOfContent = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        fileName = new javax.swing.JTextField();
        startDownloadEpub = new javax.swing.JButton();
        outputFolderBrowserBtn = new javax.swing.JButton();
        outputFolderStr = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        connection = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputTextArea = new javax.swing.JTextArea();

        javax.swing.GroupLayout jNovelChooserLayout = new javax.swing.GroupLayout(jNovelChooser.getContentPane());
        jNovelChooser.getContentPane().setLayout(jNovelChooserLayout);
        jNovelChooserLayout.setHorizontalGroup(
            jNovelChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );
        jNovelChooserLayout.setVerticalGroup(
            jNovelChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        outputFolderChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mousePressedFocusFrame(evt);
            }
        });

        findNovelBtn.setText("Tìm truyện");
        findNovelBtn.setActionCommand("Find novel");
        findNovelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findNovelBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("URL:");

        novelURL.setText("https://truyen.tangthuvien.vn/doc-truyen/");
        novelURL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                novelURLFocusLost(evt);
            }
        });
        novelURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novelURLActionPerformed(evt);
            }
        });

        jLabel2.setText("Tên truyện:");

        jLabel3.setText("Tác giả:");

        jLabel4.setText("Người đăng:");

        jLabel5.setText("Số chương:");

        novelName.setText("N/A");

        author.setText("N/A");

        uploader.setText("N/A");

        chapterNum.setText("N/A");

        jLabel6.setText("Chương đầu:");

        start.setModel(new javax.swing.SpinnerNumberModel(0, 0, 0, 0));
        start.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                startStateChanged(evt);
            }
        });

        stop.setModel(new javax.swing.SpinnerNumberModel(0, 0, 0, 0));
        stop.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                stopStateChanged(evt);
            }
        });

        jLabel7.setText("Chương cuối:");

        titleCheck.setText("title.md");

        coverCheck.setText("cover.png");

        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mousePressedFocusFrame(evt);
            }
        });

        jLabel11.setText("Tên thư mục download:");

        startDownloadMD.setText("Download");
        startDownloadMD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDownloadMDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(folderName, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(startDownloadMD)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(folderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(startDownloadMD)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Markdown folder", jPanel1);

        templateFileBrowserBtn.setText("Browse...");
        templateFileBrowserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                templateFileBrowserBtnActionPerformed(evt);
            }
        });

        jLabel10.setText("Template file:");

        backToDefaultTemplate.setText("Default");
        backToDefaultTemplate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToDefaultTemplateActionPerformed(evt);
            }
        });

        tableOfContent.setText("Mục lục");

        jLabel12.setText("Tên file:");

        startDownloadEpub.setText("Download");
        startDownloadEpub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDownloadEpubActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(templateFileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(templateFileBrowserBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(backToDefaultTemplate))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(tableOfContent)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fileName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(startDownloadEpub)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(templateFileBrowserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backToDefaultTemplate))
                    .addComponent(templateFileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tableOfContent)
                    .addComponent(jLabel12)
                    .addComponent(fileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startDownloadEpub))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Epub file", jPanel2);

        outputFolderBrowserBtn.setText("Browse...");
        outputFolderBrowserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputFolderBrowserBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("Thư mục chính:");

        connection.setModel(new javax.swing.SpinnerNumberModel(50, 1, null, 1));

        jLabel9.setText("Số chương download cùng lúc:");

        outputTextArea.setEditable(false);
        outputTextArea.setColumns(20);
        outputTextArea.setRows(5);
        jScrollPane1.setViewportView(outputTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(novelURL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(findNovelBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outputFolderStr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outputFolderBrowserBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chapterNum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stop, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(titleCheck))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(novelName)
                                            .addComponent(author))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(uploader)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(coverCheck)
                            .addComponent(connection, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findNovelBtn)
                    .addComponent(jLabel1)
                    .addComponent(novelURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(novelName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(author))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(uploader)
                    .addComponent(connection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(stop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(titleCheck)
                        .addComponent(coverCheck))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(chapterNum)
                        .addComponent(jLabel6)
                        .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputFolderStr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(outputFolderBrowserBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void startStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_startStateChanged
		folderName.setText(defaultName + "-" + start.getValue() + "-" + stop.getValue());
		fileName.setText(defaultName + "-" + start.getValue() + "-" + stop.getValue() + ".epub");
	}// GEN-LAST:event_startStateChanged

	private void stopStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_stopStateChanged
		folderName.setText(defaultName + "-" + start.getValue() + "-" + stop.getValue());
		fileName.setText(defaultName + "-" + start.getValue() + "-" + stop.getValue() + ".epub");
	}// GEN-LAST:event_stopStateChanged

	private void startDownloadMDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_startDownloadMDActionPerformed
		new Thread(() -> {
			setAllInputEnabled(false);
                        outputTextArea.setText("");
			File out = utils.FileInitializer.folderInit(outputFolderStr.getText()
					.replace("\\", "/") + "/" + folderName.getText());
			try {
				new ChaptersFetcher(book, (Integer) start.getValue(), (Integer) stop.getValue(),
						(Integer) connection.getValue(), titleCheck.isSelected(), coverCheck.isSelected(), out)
								.createFiles();
			} catch (IOException ex) {
				Logger.getLogger(MainFrame.class.getName())
						.log(Level.SEVERE, null, ex);
				JOptionPane.showMessageDialog(this, "Error occured", "Error", JOptionPane.ERROR_MESSAGE);
                                setAllInputEnabled(true);
                                return;
                        }
                        JOptionPane.showMessageDialog(this, "Succeed", "Done!", JOptionPane.OK_OPTION);
			setAllInputEnabled(true);

		}).start();
	}// GEN-LAST:event_startDownloadMDActionPerformed

	private void templateFileBrowserBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_templateFileBrowserBtnActionPerformed
		if (templateFileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
			templateFileLabel.setText(templateFileChooser.getSelectedFile()
					.getAbsolutePath());
		}
	}// GEN-LAST:event_templateFileBrowserBtnActionPerformed

	private void backToDefaultTemplateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backToDefaultTemplateActionPerformed
		templateFileLabel.setText(templateTemp.getAbsolutePath());
	}// GEN-LAST:event_backToDefaultTemplateActionPerformed

	private void startDownloadEpubActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_startDownloadEpubActionPerformed
		new Thread(() -> {
			setAllInputEnabled(false);
                        outputTextArea.setText("");
			File out;
			try {
				out = new File(outputFolderStr.getText()
						.replace("\\", "/") + "/" + fileName.getText());
				File outFolder = Files.createTempDirectory("EpubMaker")
						.toFile();
				new ChaptersFetcher(book, (Integer) start.getValue(), (Integer) stop.getValue(),
						(Integer) connection.getValue(), titleCheck.isSelected(), coverCheck.isSelected(), outFolder)
								.createFiles();
				FileUtils.forceDeleteOnExit(outFolder);
				EpubBuilder.buildEpubFromMarkdownFolder(outFolder, new File(templateFileLabel.getText()),
						tableOfContent.isSelected(), out);
			} catch (IOException ex) {
				Logger.getLogger(MainFrame.class.getName())
						.log(Level.SEVERE, null, ex);
				JOptionPane.showMessageDialog(this, "Error occured", "Error", JOptionPane.ERROR_MESSAGE);
                                setAllInputEnabled(true);
                                return;
			}
                        JOptionPane.showMessageDialog(this, "Succeed", "Done!", JOptionPane.OK_OPTION);
			setAllInputEnabled(true);
		}).start();
	}// GEN-LAST:event_startDownloadEpubActionPerformed

	private void mousePressedFocusFrame(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_mousePressedFocusFrame
		requestFocus();
	}// GEN-LAST:event_mousePressedFocusFrame

	private void findNovelBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		jNovelChooser.setVisible(true);
	}// GEN-LAST:event_jButton1ActionPerformed

	private TTVTitlePage book;
	private void novelURLActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_novelURLActionPerformed
		new Thread(() -> updateURL()).start();
	}// GEN-LAST:event_novelURLActionPerformed

	private void novelURLFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_novelURLFocusLost
		new Thread(() -> updateURL()).start();
	}// GEN-LAST:event_novelURLFocusLost

	private void outputFolderBrowserBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_outputFolderBrowserBtnActionPerformed
		File current = new File(outputFolderStr.getText());
		if (current.isDirectory()) {
			outputFolderChooser.setSelectedFile(current);
		}
		if (outputFolderChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
			outputFolderStr.setText(outputFolderChooser.getSelectedFile()
					.getAbsolutePath());
		}
	}// GEN-LAST:event_outputFolderBrowserBtnActionPerformed

	private String oldUrl = null;
	private String defaultName = null;
	public void updateURL() {
		String newUrl = novelURL.getText();
		if (!newUrl.equals(oldUrl)) {
			oldUrl = newUrl;
			novelURL.setEnabled(false);
			try {
				book = new TTVTitlePage(newUrl);
			} catch (Exception ex) {
				book = null;
			}

			if (book != null) {
				novelName.setText(book.getNovelName());
				author.setText(book.getNovelAuthor());
				Stream<String> uploaders = book.getUploader();
				uploader.setText(
						uploaders == null ? "N/A" : uploaders.reduce("", (a, b) -> a + (a.isEmpty() ? b : "," + b)));
				int chapterNumInt = book.getChapterNum();
				chapterNum.setText(Integer.toString(chapterNumInt));
				start.setModel(new SpinnerNumberModel(1, 1, chapterNumInt, 1));
				stop.setModel(new SpinnerNumberModel(chapterNumInt, 1, chapterNumInt, 1));
				start.setEnabled(true);
				stop.setEnabled(true);
				String[] tokens = newUrl.split("/");
				defaultName = tokens[tokens.length - 1];
				folderName.setText(defaultName);
				fileName.setText(defaultName + ".epub");
				startDownloadMD.setEnabled(true);
				startDownloadEpub.setEnabled(true);
			} else {
				novelName.setText("N/A");
				author.setText("N/A");
				uploader.setText("N/A");
				chapterNum.setText("N/A");
				start.setModel(new SpinnerNumberModel(0, 0, 0, 0));
				stop.setModel(new SpinnerNumberModel(0, 0, 0, 0));
				start.setEnabled(false);
				stop.setEnabled(false);
				startDownloadMD.setEnabled(false);
				startDownloadEpub.setEnabled(false);
			}
			novelURL.setEnabled(true);
		}
	}

	private void setAllInputEnabled(boolean state) {
		novelURL.setEnabled(state);
		findNovelBtn.setEnabled(state);
		connection.setEnabled(state);
		start.setEnabled(state);
		stop.setEnabled(state);
		titleCheck.setEnabled(state);
		coverCheck.setEnabled(state);
		outputFolderStr.setEnabled(state);
		outputFolderBrowserBtn.setEnabled(state);
		templateFileBrowserBtn.setEnabled(state);
		backToDefaultTemplate.setEnabled(state);
		tableOfContent.setEnabled(state);
		fileName.setEnabled(state);
		startDownloadEpub.setEnabled(state);
		folderName.setEnabled(state);
		startDownloadMD.setEnabled(state);
	}
	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					new MainFrame().setVisible(true);
				} catch (IOException ex) {
					Logger.getLogger(MainFrame.class.getName())
							.log(Level.SEVERE, null, ex);
				}
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel author;
    private javax.swing.JButton backToDefaultTemplate;
    private javax.swing.JLabel chapterNum;
    private javax.swing.JSpinner connection;
    private javax.swing.JCheckBox coverCheck;
    private javax.swing.JTextField fileName;
    private javax.swing.JButton findNovelBtn;
    private javax.swing.JTextField folderName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JDialog jNovelChooser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel novelName;
    protected javax.swing.JTextField novelURL;
    private javax.swing.JButton outputFolderBrowserBtn;
    private javax.swing.JFileChooser outputFolderChooser;
    private javax.swing.JTextField outputFolderStr;
    private javax.swing.JTextArea outputTextArea;
    private javax.swing.JSpinner start;
    private javax.swing.JButton startDownloadEpub;
    private javax.swing.JButton startDownloadMD;
    private javax.swing.JSpinner stop;
    private javax.swing.JCheckBox tableOfContent;
    private javax.swing.JButton templateFileBrowserBtn;
    private javax.swing.JFileChooser templateFileChooser;
    private javax.swing.JLabel templateFileLabel;
    private javax.swing.JCheckBox titleCheck;
    private javax.swing.JLabel uploader;
    // End of variables declaration//GEN-END:variables
}
